CREATE TABLE employee (
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	identity_number VARCHAR(125) NOT NULL,
	nationality VARCHAR(255) NOT NULL,
	citizenship_country VARCHAR(255) NOT NULL,
	date_of_birth DATE NOT NULL,
	place_of_birth VARCHAR(255) NOT NULL,
	address TEXT NOT NULL,
	phone_number VARCHAR(125) NOT NULL,
	email VARCHAR(255) NOT NULL,
	bank_name VARCHAR(255) NOT NULL,
	bank_account_number BIGINT NOT NULL,
	has_drivers_license BOOLEAN NOT NULL,
	starting_date DATE NOT NULL,
	finishing_date DATE NOT NULL,
	salary_per_hour DOUBLE PRECISION,
	contract_type VARCHAR(255) NOT NULL,
	PRIMARY KEY (identity_number)
);