CREATE TABLE vehicle (
	car_model VARCHAR NOT NULL,
	plate_number VARCHAR NOT NULL,
	vehicle_identification_number BIGINT NOT NULL,
	insurance_type VARCHAR NOT NULL,
	gps_number VARCHAR NOT NULL,
	owners_name VARCHAR NOT NULL,
	tuf_expiration_date DATE NOT NULL,
	insurance_expiration_date DATE NOT NULL,
	oil_change_indicator INT NOT NULL,
	fuel_injector_change_indicator INT NOT NULL,
	fuel_injector_filter_change_required BOOLEAN,
	anti_frost_change_required_change_required BOOLEAN,
	air_filter_change_required BOOLEAN,
	inside_air_filter_change_required BOOLEAN,
	brake_fluid_change_required BOOLEAN,
	project_id INT,
	PRIMARY KEY (vehicle_identification_number),
	CONSTRAINT FK_project_id FOREIGN KEY(project_id) REFERENCES project(project_code)
);