CREATE TABLE vehicle(
    id BIGINT NOT NULL,
    model VARCHAR NOT NULL,
    brand VARCHAR NOT NULL,
    plate_number VARCHAR NOT NULL,
    vin BIGINT NOT NULL,
    mileage INT NOT NULL,
    tire_type VARCHAR NOT NULL,
    insurance_type VARCHAR NOT NULL,
    dkv_number VARCHAR,
    gps_number VARCHAR NOT NULL,
    owners_name VARCHAR,
    tuf_expiration_date DATE NOT NULL,
    insurance_expiration_date DATE,
    oil_change_indicator INT,
    fuel_injector_change_indicator INT,
    timing_belt_change_indicator INT,
    adBlue_change_indicator INT,
    fuel_injector_filter_change_required boolean,
    anti_frost_change_required_change_required boolean,
    air_filter_change_required boolean,
    inside_air_filter_change_required boolean,
    brake_fluid_change_required boolean,
    project_id INT,
    PRIMARY KEY(id),
    CONSTRAINT fk_project_id FOREIGN KEY(project_id) REFERENCES project(id)
);